-- ========================================================
-- AM Star Transmissions - initial schema
-- Tables are creating in dependency order; do not reorder.
-- ========================================================

-- users: app logins only. 3 admins + 1 shared shop view.
create table users (
  id bigint generated by default as identity primary key,
  email varchar(160) not null unique,
  username varchar(50) not null,
  password_hash varchar(100) not null, -- BCrypt output is 60 chars
  role varchar(20) not null default 'SHOP_VIEW',
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  constraint users_role_valid check (role in ('ADMIN', 'SHOP_VIEW'))
);

-- customers: the vehicle owner as a record. Never a login.
create table customers (
  id bigint generated by default as identity primary key,
  full_name varchar(120) not null,
  phone varchar(20),
  email varchar(160),
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index idx_customers_name on customers (lower(full_name));
create index idx_customers_phone on customers (phone);

-- vehicles: one row per real car, reused across visits.
create table vehicles (
  id bigint generated by default as identity primary key,
  customer_id bigint references customers(id) on delete set null,
  vin varchar(17),
  license_plate varchar(12),
  state varchar(2),
  make varchar(60),
  model varchar(60),
  model_year integer,
  car_image_url varchar(2000),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint vehicles_year_sane
    check (model_year is null or model_year between 1900 and 2100),
  constraint vehicles_identifiable
    check (vin is not null or license_plate is not null)
);

-- Dedupe: a full 17 char VIN is globally unique; a plate is unique per state.
-- Partial indexes so blank/short VINs from failed NHTSA lookups don't collide.
create unique index uq_vehicles_vin
  on vehicles (upper(vin))
  where vin is not null and length(vin) = 17;

create unique index uq_vehicles_plate
  on vehicles (upper(license_plate), state)
  where license_plate is not null;

-- service_tickets: the work order.
create table service_tickets (
  id bigint generated by default as identity primary key,
  vehicle_id bigint not null references vehicles(id) on delete restrict,
  customer_id bigint references customers(id) on delete set null,
  severity integer not null,
  status varchar(20) not null default 'PENDING',
  entry_date date not null default current_date,
  expected_completion_date date not null,
  actual_completion_date date,
  retail_price numeric(10,2) not null default 0,
  lease_price numeric(10,2) not null default 0,
  labor_price numeric(10,2) not null default 0,
  include_retail boolean not null default false,
  include_lease boolean not null default false,
  include_labor boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint tickets_severity_range check (severity between 1 and 5),
  constraint tickets_status_valid
    check (status in ('PENDING', 'IN_PROGRESS', 'COMPLETED')),
  constraint tickets_price_non_negative
    check (retail_price >= 0 and lease_price >= 0 and labor_price >= 0),
  -- Mirrors PriorityQueueService.updateRepairStatus in both directions:
  -- COMPLETED stamps the date, any other status clears it.
  constraint tickets_completion_matches_status
    check ((status = 'COMPLETED') = (actual_completion_date is not null)),
  constraint tickets_completed_after_entry
    check (actual_completion_date is null or actual_completion_date >= entry_date)
);

create index idx_tickets_status on service_tickets (status);
create index idx_tickets_vehicle on service_tickets (vehicle_id);
create index idx_tickets_customer on service_tickets (customer_id);
create index idx_tickets_due on service_tickets (expected_completion_date);

-- technicians: the shop roster. Deactivated, never deleted.
create table technicians (
  id bigint generated by default as identity primary key,
  full_name varchar(120) not null,
  phone varchar(20),
  hired_on date,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index uq_technicians_name on technicians (lower(full_name));

-- services: the catalog. Names normalized uppercase.
create table services (
  id bigint generated by default as identity primary key,
  name varchar(80) not null,
  default_severity integer not null default 3,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint services_severity_range check (default_severity between 1 and 5),
  -- Makes the frontend's uppercase normalization non-optional
  constraint services_name_uppercase check (name = upper(name))
);

create unique index uq_services_name on services (name);

-- ticket_technicians: who worked on what.
-- CASCADE toward the ticket (deleting a ticket cleans up its own links),
-- RESTRICT toward the technician (history must keep pointing at a real row).
create table ticket_technicians (
  ticket_id bigint not null references service_tickets(id) on delete cascade,
  technician_id bigint not null references technicians(id) on delete restrict,
  assigned_at timestamptz not null default now(),
  primary key (ticket_id, technician_id)
);

create index idx_ticket_techs_tech on ticket_technicians (technician_id);

-- ticket_services: what work the ticket covers.
create table ticket_services (
  ticket_id bigint not null references service_tickets(id) on delete cascade,
  service_id bigint not null references services(id) on delete restrict,
  primary key (ticket_id, service_id)
);

create index idx_ticket_services_service on ticket_services (service_id);

-- updated_at maintenance
-- Enforced in the database so it stays correct no matter what writes the row.
create or replace function set_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

create trigger trg_customers_updated_at before update on customers
  for each row execute function set_updated_at();
create trigger trg_vehicles_updated_at before update on vehicles
  for each row execute function set_updated_at();
create trigger trg_service_tickets_updated_at before update on service_tickets
  for each row execute function set_updated_at();
create trigger trg_technicians_updated_at before update on technicians
  for each row execute function set_updated_at();
create trigger trg_services_updated_at before update on services
  for each row execute function set_updated_at();

