-- Single-use, expiring password reset tokens.
-- Only a SHA-256 hash is stored: a leaked database must not yield
-- working reset links, the same reason password_hash exists.
create table password_reset_tokens (
  id bigint generated by default as identity primary key,
  user_id bigint not null references users(id) on delete cascade,
  token_hash varchar(64) not null unique,
  expires_at timestamptz not null,
  used_at timestamptz,
  created_at timestamptz not null default now()
);

create index idx_reset_tokens_user on password_reset_tokens (user_id);
