-- Who changed what on a ticket, and when. Feeds the dashboard activity feed.

-- ticket_id in ON DELETE SET NULL, and the label is a snapshot taken when the
-- event happended, so a deleted ticket's history still reads correctly.
create table ticket_activity (
  id bigint generated by default as identity primary key,
  ticket_id bigint references service_tickets(id) on delete set null,
  ticket_label varchar(200) not null,
  actor varchar(160) not null,
  action varchar(20) not null,
  detail varchar(500),
  created_at timestamptz not null default now(),

  constraint activity_action_valid check (action in
    ('CREATED', 'STATUS', 'SEVERITY', 'ASSIGNED', 'SERVICES', 'PRICING', 'NOTES', 'DELETED'))
);

create index idx_activity_created on ticket_activity (created_at desc);
